# Site settings
title: Ronald Mosquera
description: Introdduccion a la ingenieria en software
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Ronald Mosquera
user_description: Soy estudiante de la universidad de guayaquil en la carrera de ingenieria de software, cursando el primer semestre, en esta pagina web mostrare las clases dadas en introduccion a la ing.en software</a>
email: ronald.mosqueram@ug.edu.ec
# github_username:  lorem_ipsum


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
